### PR TITLE
Add list query to "Dropdown (SQL filled") attribute

### PR DESCRIPTION
**Pull request by mmitteregger-bearingpoint**
The edit query (previously the only query for this attribute type) was only executed once in the ci list for all attributes.
The first ci id was used as placeholder and the result list was taken for the display of all other attribute values.
When the ci id was used as restriction in the query, other selected attribute values were not fetched and couldn't be displayed.

The reason for this is performance. Executing the edit query once for every attribute value in the list slows down the page load way too much.

So this commit adds another query - the list query - to this individual attribute options.
This allows the operator to provide a query with restrictions using the ci id for editing and provide a separate query which is executed once for the list view without those restrictions.

The new list query is optional.
When empty (like for all existing attributes) the edit query will be used to retain backwards compatibility.

### CODE REVIEW

**Review by markooslaj — CHANGES_REQUESTED** [review]
The list_query value in infoCMDB_history.attribute_default_queries is not updated when you change values. The query value is updated.

**Comment by mmitteregger-bearingpoint** [comment]
> The list_query value in infoCMDB_history.attribute_default_queries is not updated when you change values. The query value is updated.

Nice find.
I've added a new commit that addresses that issue. The list_query history should now be written correctly similar to the query column.

**Review by markooslaj — CHANGES_REQUESTED** [review]
Still not working, the result is the same.
In infoCMDB_history.attribute_default_queries is the list_query value empty.
The information is not so important, but good to know if someone makes a change.

**Comment by mmitteregger-bearingpoint** [comment]
I did not want to introduce a separate migration for this, so I have added the fix directly to the 20200309095933_add_list_query migration.

Did you re-execute this migration for your test?
```shell
infocmdb# ./run bash
/app# cd deploy/
/app/deploy# ./phinx status
...
     up  20200309095933  ... ... AddListQuery
/app/deploy# ./phinx rollback -t 20200225152608
...
 == 20200309095933 AddListQuery: reverting
 == 20200309095933 AddListQuery: reverted 0.0750s
...
/app/deploy# ./phinx status
...
   down  20200309095933                                            AddListQuery
/app/deploy# ./phinx migrate
...
 == 20200309095933 AddListQuery: migrating
 == 20200309095933 AddListQuery: migrated 0.0695s
/app/deploy# ./phinx status
...
     up  20200309095933  ... ...  AddListQuery
```
Note that this workaround is only needed when you migrate AddListQuery without the second fix commit, which won't happen on already deployed instances.

**Review by markooslaj — APPROVED** [review]
Everything is working now.
I had to re-execute the migration.

**Pull request merged**
